name       : nbd
version    : '3.19'
release    : 1
source     :
    - https://downloads.sourceforge.net/nbd/nbd-3.19.tar.xz : b4466412f13e057659f25d35e1e8e181afd62c7179bff22a6add81445ecb8690
license    : GPL-2.0
component  : system.utils
summary    : NBD userland client.
description: |
    This package contains nbd-server and nbd-client.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(glib-2.0)
    - pkgconfig(libnl-genl-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/nbd/config
    install -Dm00644 $pkgfiles/nbd.service  $installdir/%libdir%/systemd/system/nbd.service
    install -Dm00644 $pkgfiles/nbd.sysusers $installdir/%libdir%/sysusers.d/nbd.conf
