name       : nbd
version    : '3.24'
release    : 6
source     :
    - https://github.com/NetworkBlockDevice/nbd/releases/download/nbd-3.24/nbd-3.24.tar.xz : 6877156d23a7b33f75eee89d2f5c2c91c542afc3cdcb636dea5a88539a58d10c
homepage   : https://nbd.sourceforge.io/
license    : GPL-2.0-or-later
component  : network.util
summary    : Network Block Device Server and Client Utilities
description: |
    Tools for network block devices, allowing you to use remote block devices over TCP/IP.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(glib-2.0)
    - pkgconfig(libnl-genl-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/nbd/config
    install -Dm00644 $pkgfiles/nbd.service  $installdir/%libdir%/systemd/system/nbd.service
    install -Dm00644 $pkgfiles/nbd.sysusers $installdir/%libdir%/sysusers.d/nbd.conf
