name       : nbd
version    : '3.21'
release    : 3
source     :
    - https://sourceforge.net/projects/nbd/files/nbd/3.21/nbd-3.21.tar.xz/download : e7688af39d91733bbcd2db08062c44fe503d004e51528740139c44aff6a6bef9
license    : GPL-2.0-or-later
component  : system.utils
summary    : NBD userland client.
description: |
    This package contains nbd-server and nbd-client.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(glib-2.0)
    - pkgconfig(libnl-genl-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/nbd/config
    install -Dm00644 $pkgfiles/nbd.service  $installdir/%libdir%/systemd/system/nbd.service
    install -Dm00644 $pkgfiles/nbd.sysusers $installdir/%libdir%/sysusers.d/nbd.conf
